// <auto-generated />
using System;
using Ellipse.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ellipse.Data.Migrations
{
    [DbContext(typeof(EllipseDbContext))]
    [Migration("20260713201728_AddRequestTable")]
    partial class AddRequestTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Ellipse.Data.Entities.Request", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdditionalUserAccess")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BusinessJustification")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EllipsePosition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("EllipseUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("HCSystemsAdminApproved")
                        .HasColumnType("bit");

                    b.Property<int?>("HcAdminApprovalId")
                        .HasColumnType("int");

                    b.Property<int?>("ICTManagerApprovalId")
                        .HasColumnType("int");

                    b.Property<bool?>("ICTManagerApproved")
                        .HasColumnType("bit");

                    b.Property<int?>("LineManagerApprovalId")
                        .HasColumnType("int");

                    b.Property<bool?>("LineManagerApproved")
                        .HasColumnType("bit");

                    b.Property<string>("MenuAccess")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("MissingDocuments")
                        .HasColumnType("bit");

                    b.Property<bool?>("RequestClosed")
                        .HasColumnType("bit");

                    b.Property<string>("RequestType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RequestedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TemporaryPosition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TemporaryPostId")
                        .HasColumnType("int");

                    b.Property<int?>("TrainingApprovalId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TrainingCompletionDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("TrainingVerified")
                        .HasColumnType("bit");

                    b.Property<string>("UserAccessType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("userId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Requests");
                });
#pragma warning restore 612, 618
        }
    }
}
